[window]
decorations = "None"
opacity = 0.8

[selection]
save_to_clipboard = true

[font]
size = 12.0

[font.normal]
family = "JetBrains Mono"
style = "SemiBold"

[font.bold]
family = "JetBrains Mono"
style = "Bold"

[font.italic]
family = "JetBrains Mono"
style = "Italic"

[font.bold_italic]
family = "JetBrains Mono"
style = "Bold Italic"

[general]
import = [
    "~/.config/alacritty/themes/themes/gruvbox_dark.toml"
]
